name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
        
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o Sender testSender.cpp Sender.c   
      
    - name: build 
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o Receiver testReceiver.cpp Receiver.c
      
    - name: run Sender
      run: ./Sender 
      
    - name: Pipeline Sender/Receiver
      run: ./Sender | ./Receiver
 
    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 2
